### ISSUE TITLE
Needs to work with PHP 8

### ISSUE THREAD

**Issue by majurgens** [russellvt/pnp4nagios#3]
The last pnp4nagios code does not work with PHP 8

**Comment by tjyang** [comment]
@majurgens 
Can you provide your compilation steps/logs  here ?

**Comment by majurgens** [comment]
No. I did not compile it. I am using this Fedora package pnp4nagios-0.6.25-3.fc24.x86_64

**Comment by tjyang** [comment]
@majurgens 
I am no php developer and I found kohana that pnp4nagios depends on is deprecated also.
See https://github.com/koseven/koseven/
